### ISSUE TITLE
哇哇大哭之插件炸裂【BUG】

### ISSUE THREAD

**Issue by Mia0a-hi** [lsp84ch83/toolbox#2]
首先作者有备份使我开心，其次出现了问题：
<img width="610" alt="7b1c1b8876854d7121f20ea5db317a4" src="https://github.com/lsp84ch83/toolbox/assets/40627909/f6e0592a-aeda-4ffa-b7dd-19760d1e2f49">
<img width="621" alt="c7f90b9461c3f67e70a5769a0c09c48" src="https://github.com/lsp84ch83/toolbox/assets/40627909/de5b14f3-0862-4ec1-9df9-53691192096d">
打马的地方均为路径：
![image](https://github.com/lsp84ch83/toolbox/assets/40627909/4444f5bb-732a-475b-b18e-19b8e72beb52)

**Comment by lsp84ch83** [comment]
> 首先作者有备份让我很高兴，其次出现了问题： 打马的路径后续路径： <img alt="7b1c1b8876854d7121f20ea5db317a4" width="610" src="https://private-user-images.githubusercontent.com/40627909/310351358-f6e0592a-aeda-4ffa-b7dd-19760d1e2f49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNDAwMDYsIm5iZiI6MTcxMDIzOTcwNiwicGF0aCI6Ii80MDYyNzkwOS8zMTAzNTEzNTgtZjZlMDU5MmEtYWVkYS00ZmZhLWI3ZGQtMTk3NjBkMWUyZjQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDEwMzUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4MTI5YzIyYmMxMzA5M2NlZDNiMDdhYzQxOGY0NmZmYTdkODRkNjRkYmViMWVjZTk3ZTEyYWRkNjhiODgzMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fgpKiQS29GLBJ6kEUELAdrWPKz0fC7YfLSrfCJCIbvA"> <img alt="c7f90b9461c3f67e70a5769a0c09c48" width="621" src="https://private-user-images.githubusercontent.com/40627909/310351375-de5b14f3-0862-4ec1-9df9-53691192096d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNDAwMDYsIm5iZiI6MTcxMDIzOTcwNiwicGF0aCI6Ii80MDYyNzkwOS8zMTAzNTEzNzUtZGU1YjE0ZjMtMDg2Mi00ZWMxLTlkZjktNTM2OTExOTIwOTZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDEwMzUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiMzk0Nzg1NWYxMjA3MWRkNjZhY2UwNGZkNWQ0MjUxMTcyNDQ4ZTcwNDgyZjg2N2Q3MDQ1Y2Y2NGQ3ZWM4NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t9Wn9UbFjgoYMAP51cFJVeANl-2QuYMvOr2APrT67ew"> ![图像](https://private-user-images.githubusercontent.com/40627909/310351600-4444f5bb-732a-475b-b18e-19b8e72beb52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNDAwMDYsIm5iZiI6MTcxMDIzOTcwNiwicGF0aCI6Ii80MDYyNzkwOS8zMTAzNTE2MDAtNDQ0NGY1YmItNzMyYS00NzViLWIxOGUtMTliOGU3MmJlYjUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDEwMzUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3OGU1MmVkOTAwMDgwN2U4NGQ0MzFjYzczNWM2YWFjNGQ4ZTk1YmE2ZTk1OGIyNTNkYzQ5YTQyMWRiYTI2OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U-o6l_oe9LFKUl0UJf7y-FZxeBn7ObjOGX9mM1pld9k)

这个应该是编码的问题，你可以尝试打开一个配置文件看下文字是否乱码，乱码的话可以尝试调整写入时的编码

**Comment by lsp84ch83** [comment]
您好，很抱歉无法在第一时间给您回复，看到来信时我会尽快给您回复。
